services:
  - type: web
    name: helmet-inventory
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn helmet_inventory.wsgi:application
    runtime: python-3.12.3
